janet-lang/janet-lang.org

md/strings.md

Keywords start with a colon, not a semicolon

---

md/data_structures.md

I'd like to know the available operations and their complexity on the built-in data structures. Instead of just asking I created a small table and made some wild guesses :) If you agree with the changes you could edit the table and accept the PR.

adds more useful information about data structures

---

content/docs/syntax.mdz

Check and improve two paragraphs with Grammarly. Feel free to close it after inspection.

Just the taste of how Grammarly check will look like.

---

content/docs/index.mdz
content/docs/jpm.mdz
content/docs/modules.mdz
static/1.3.1/docs/index.html
static/1.3.1/docs/modules.html
static/1.3.1/introduction.html
static/1.4.0/docs/index.html
static/1.4.0/docs/jpm.html
static/1.4.0/docs/modules.html
static/1.4.0/introduction.html
static/1.5.0/docs/index.html
static/1.5.0/docs/modules.html
static/1.5.0/introduction.html

Minor updates to spelling and capitalization.

Fix typos in documentation

---

content/docs/data_structures/arrays.mdz

resolves https://github.com/janet-lang/janet/issues/362

update documentation gregarding the `in` array function

---

content/docs/strings.mdz

- "there" --> "their"
- remove unnecessary "very"
- "for for" --> "for"

Strings docs fixes

---

content/docs/threads.mdz

- formatting bug
- verbiage tweak
- typo

threads: fixups

---

content/docs/peg.mdz

I just copied text from the message of the commit which introduced it.

Add lenprefix pattern capture

---

Makefile
content/api/gen-docs.janet

Reverts janet-lang/janet-lang.org#57

Revert "Add C source links to the website."

---

static/1.8.1/index.html
templates/index.html

b = bit
B = byte
https://en.wikipedia.org/wiki/Byte#Unit_symbol

Replace 'Mb' with 'MB'

---

content/capi/configuration.mdz

Hi! Just something that had caught my eye skimming the docs.
I hope editing every version is the right approach here -- is it? 😃

configuration: "turned of" -> "turned off"

---

content/docs/jpm.mdz

Feel free to change the wording, or adjust this PR. Overall I just think its important we show how to do local installs.

Prominently explain local install

---

content/docs/index.mdz

Updates Windows instructions wrt building from source and installing

---

content/docs/abstract_machine.mdz
content/docs/bindings.mdz
content/docs/comparison.mdz
content/docs/destructuring.mdz
content/docs/flow.mdz
content/docs/functions.mdz
content/docs/jpm.mdz
content/docs/loop.mdz
content/docs/macros.mdz
content/docs/modules.mdz
content/docs/object_oriented.mdz
content/docs/peg.mdz
content/docs/prototypes.mdz
content/docs/strings.mdz
content/docs/threads.mdz

Document comparison in Janet -- including polymorphic comparison

---

content/docs/functions.mdz

Some suggestions for minor changes.

Tweaks to functions doc

---

content/api/ev.mdz
content/capi/index.mdz
content/docs/data_structures/index.mdz
content/docs/index.mdz
content/docs/peg.mdz
content/docs/specials.mdz
content/docs/strings.mdz
content/docs/syntax.mdz

Typo on the docs jumped out to me, so I did a spell check on the rest.

Spellcheck docs

---

content/docs/data_structures/buffers.mdz

Modify the values of `set` special form to be different with ones of `put`

Modify the values of `set` special form to be differently with ones of `put`

---

content/capi/memory-model.mdz

Suggestions for inserting a few words here and there.

Minor suggestions in text

---

content/capi/writing-c-functions.mdz

Suggestion of the addition of one word.

Minor suggestion in text

---

content/capi/writing-c-functions.mdz

An attempt to address https://github.com/janet-lang/janet-lang.org/issues/135

Add %c to formatted error messages table

---

content/docs/event_loop.mdz

Mostly minor tweaks including some code indentation changes.
Includes some removal of what I thought were references to older thread functionality.

Tweaks to event loop docs

---

content/docs/event_loop.mdz

event_loop.mdz: Typo fix

---

content/docs/threads.mdz

Some minor tweaks including removal of what appears to be a fragment of a sentence from the older docs.

Tweak threads doc

---

content/docs/destructuring.mdz

document "& more"

---

content/docs/documentation.mdz
content/docs/strings.mdz
content/docs/syntax.mdz

terminology, "long-strings"

---

content/docs/index.mdz

Add a "your second program" section which documents how Janet handles a `main` function (addresses #87 ), as well as whet's the appetite for more Janet.
Also, World is a proper name here, so I capitalized it.

index.mdz, add 2nd first program, document main

---

templates/docpage.html
templates/index.html

Tweak path to favicon in some templates

---

content/docs/threads.mdz

threads.mdz: Typo fixes

---

content/docs/syntax.mdz

Re: https://github.com/janet-lang/janet/pull/1116

Tweak peg for long-bytes

---

content/docs/syntax.mdz

Now it should be clearer to understand

Update syntax > long string

---

content/docs/peg.mdz

document true and false PEG primitives

---

content/docs/peg.mdz

reference: https://github.com/janet-lang/janet/pull/1187#issuecomment-1586490024

Document peg grammar: 0

---

content/docs/modules.mdz

This PR is an attempt to address #207.

Document import search order

---

examples/++.janet

I had originally contributed this as part of a larger PR, but I am resubmitting as single files per @sogaiu 's recommendation to make reviews more manageable and focused.

Add example for ++

---

examples/string_47trimr.janet

add examples for string/trimr

---

examples/has-key_63.janet
examples/has-value_63.janet

add examples for has-key? and has-value?

add examples for has-key? and has-value?

---

examples/distinct.janet

add examples for distinct

---

examples/empty_63.janet

add examples for empty?
