janet-lang/janet-lang.org

tools/templater.janet

The day number from os/date is 0-indexed. Adding 1 before formatting so the human-readable date is correct.

Fixing day number in nice-day

---

md/syntax.md

Description of nil and NaN as keys and values in structs and tables is now consistent with current behavior. Not sure if NaN as value behavior is intended.

Grammar, spelling and nil and NaN as K/V

---

src/css/landing.css
templates/index.html

This fixes the behavior where you could click outside the button to activate it, even though the button wasn’t highlighted as it is on hover.
This also simplifies the HTML; the `div` elements are unnecessary.
related to issue #6

Fix too-large click areas on home page buttons

---

content/docs/index.mdz

Janet is [now available][1] through homebrew. Added instructions to the installation guide.
[1]: https://github.com/Homebrew/homebrew-core/commit/7cdb4a0f5daebd718c2fe973b3b449ff356ac534

Add macos homebrew installation instructions

---

content/docs/syntax.mdz

On https://janet-lang.org/docs/syntax.html, there is a link to https://janet-lang.org/peg.html, it doesn't work, it should be https://janet-lang.org/docs/peg.html

Fix link to peg.html

---

content/docs/modules.mdz

Fixes a few minor typos and misspellings in the Modules documentation.

Fix typos in Modules documentation

---

content/docs/fibers/error_handling.mdz

Fixes minor grammar and spelling errors in Error Handling documentation.

Fix typos in Error Handling documentation

---

content/docs/strings.mdz

Fix peg link in the strings docs

---

examples/reverse.janet

Perhaps for reverse it should be:
```
(reverse [1 2 3]) # -> @[3 2 1]
```

Return value suggestion

---

content/docs/flow.mdz

Apart from substituting `case` for `switch`, there are a few attempts at filling in descriptions for `case` and `when`.

Minor tweak and fleshing out

---

content/docs/destructuring.mdz

Adds some code to clarify how the destructing works with a table / struct similar to the other examples on the page.
When I first read this example it was not clear to me what symbols were being bound; I think this helps show the result better.

destructuring docs: add example output

---

content/docs/object_oriented.mdz

- When reading the docs from start to end, the section on prototypes is not before this section.
- small typos / verbiage tweaks

object oriented docs: verbiage tweaks, fix some typos

---

content/docs/data_structures/tuples.mdz

I found this page difficult to understand when I first read it.
This PR contains some non-trivial editing of the content on this page. I hope these changes are 1) accurate with respect to Janet and 2) clear in their explanation of tuples.

tuples docs: fix typos, editing, add examples

---

content/capi/index.mdz
content/docs/jpm.mdz

There are two references to `cook`. This PR removes those references.

Remove references to cook

---

content/capi/embedding.mdz

Looking at embedding Janet, noticed this typo.
In Janet's README there is an outdated reference to janetconf.h as well, I am going to fix that in a bit

fix typo in capi documentation

---

content/capi/index.mdz

The example includes `const` in the function signature of `mymod`. According to [discussions on Gitter](https://gitter.im/janet-language/community?at=5ebf6b4d90f6db31beec8c4e), this is incorrect and is the cause of the warning:
```
warning: initialization of ‘Janet (*)(int32_t,  Janet *)’ {aka ‘union Janet (*)(int,  union Janet *)’} from incompatible pointer type ‘Janet (*)(int32_t,  const Janet *)’ {aka ‘union Janet (*)(int,  const union Janet *)’} [-Wincompatible-pointer-types]
```
This PR updates the signature.

Remove unnecessary const in function signature

---

content/docs/abstract_machine.mdz
content/docs/bindings.mdz
content/docs/data_structures/arrays.mdz
content/docs/data_structures/buffers.mdz
content/docs/data_structures/index.mdz
content/docs/data_structures/structs.mdz
content/docs/data_structures/tables.mdz
content/docs/data_structures/tuples.mdz
content/docs/destructuring.mdz
content/docs/fibers/dynamic_bindings.mdz
content/docs/fibers/error_handling.mdz
content/docs/fibers/index.mdz
content/docs/flow.mdz
content/docs/functions.mdz
content/docs/index.mdz
content/docs/jpm.mdz
content/docs/loop.mdz
content/docs/macros.mdz
content/docs/modules.mdz
content/docs/numbers.mdz
content/docs/object_oriented.mdz
content/docs/peg.mdz
content/docs/prototypes.mdz
content/docs/specials.mdz
content/docs/strings.mdz
content/docs/syntax.mdz
content/docs/threads.mdz
content/index.mdz

This PR really consists of two parts.
First, I have gone through each of the pages in the docs (excluding API pages) and tried to make the style consistent. This means using capitalisation and HTML `code` spans consistently and cleaning up little typos here and there. This comprises all but the last commit in this branch.
Second, I have gone through each of the same pages and wrapped the text consistently at 80 characters. I realise this is a rather personal thing and there may be reasons to prefer a different level so I made all these changes as a single commit so that they could be easily reverted.
I hope this is helpful but if there are any changes you would like me to make, please let me know.

Clean up style across documentation

---

content/docs/peg.mdz

Attempted to document `repeat`, its alias, and `backmatch`.
Also includes some minor tweaks.

Additions and tweaks to the peg docs

---

content/docs/syntax.mdz

This PR includes a couple of tweaks to the janet peg sample at: https://janet-lang.org/docs/peg.html
1) The first has to do with additional escapes for strings (i.e. `\u....` and `\U......`).  For reference, spork's `fmt.janet` currently has: https://github.com/janet-lang/spork/blob/2e227d4ec8492ee3b51fa7c591e83f126e9e1ad8/spork/fmt.janet#L22-L23
The included change for this just uses newer notation.
2) The other has to do with recognition of things that initially overlap with `:constant` (i.e. `false`, `nil`, `true`).  As an example, `nila` appears to be recognized as two things `nil` and `a`.  Presumably, one would prefer `nila` to be recognized as a single symbol.
May be there's a better way to do this than what's in this PR.
Any ideas?

Tweaks to janet peg sample

---

content/docs/syntax.mdz

This PR attempts to update the list of legal characters for use in symbols.
The characters removed from the list include:
* `|`
* `~`
* `\`
* `,`
IIUC, these are all reserved for other purposes now (except for the backslash which appears reserved for the future) at least in typical use -- though it does seem possible to create symbols with them using for example:
```
(symbol "~a")
```
I thought it might be preferable to not list them in the doc page, at least not without further clarification or warning.
The PR also tweaked:
```
@code`\@` -> @code`@`
@code` _` -> @code`_`
```
The former is a deletion of a backslash and the latter is a deletion of space

Prune legal symbol character list

---

content/docs/peg.mdz

This is an attempt to update docs for: https://github.com/janet-lang/janet/commit/6c917f686ac6f9342e5dc2d29dd769dfcbd02dd9

Add :h, :h*, :h+, :H to built-in pattern table

---

content/capi/index.mdz

Without the leading slash it just looks in janet's sources instead of the local directory and failss

Update C API docs on importing native module

---

content/docs/documentation.mdz
content/docs/jpm.mdz

I thought it might be helpful to have a documentation page explaining the basics of how docstrings work. I'm not sure where precisely to put it so just stuck it after the event loop and before the jpm pages.
Let me know if there's anything I should change.

Add documentation page

---

content/docs/fibers/error_handling.mdz

Adds a section on the error handling page about `protect`. `protect` and `try` seem to be equally "first-class" in terms of conveniences exposed around fiber errors, so let's document both.

Cover both `try` and `protect` in error section

---

content/docs/peg.mdz

This seems to work:
```
repl:1:> (peg/match ~(sequence "a" (line :a) (backref :a)) "a")
@[1 1]
```
If that's correct behavior (as well as for `column`) may be the table entries for them can be updated to have the `?tag` argument.

Add optional tag arg to line and column docs

---

content/docs/jpm.mdz

The `jpm` docs contain an example to print command-line arguments on a single line, separated by commas. A function `interpolate` is used which (as far as I can tell) does not exist. This PR changes the example to use `interpose` which produces the same result.

Change non-existent function 'interpolate' to 'interpose' in jpm docs

---

content/docs/peg.mdz

Tweaks to `:s` and `:h` information in the `default-peg-grammar` table.

Update default-peg-grammar table

---

content/docs/peg.mdz

An attempt to update the error peg special docs to mention that the `patt` argument is now optional plus description of behavior if the argument is not provided.

Update error peg special docs

---

examples/loop.janet

Update loop example to use `:in` instead of `:generate`.
Thanks to @Alligator for reporting.

Use :in instead of :generate in loop example

---

content/capi/memory-model.mdz

The arguments to `janet_tuple_n` are `(const Janet *values, int32_t n)`, according to https://github.com/janet-lang/janet/blob/5c05dec65ae4b49e65b01f96984b81c8ca774ad4/src/core/tuple.c#L50, so the second argument to it in this sample code should be `argc` rather than `argv`.

Fix error in memory management sample code

---

content/docs/loop.mdz

Minor spelling suggestion

---

content/docs/strings.mdz

Namely
(string/slice "abcdefg" 2 5) # -> "cde"

strings.mdz: Add another example to string/slice

---

content/api/gen-docs.janet

Currently, the function for generating GitHub links in the API docs assumes everything is defined in `/src/boot/boot.janet` and hard codes this as part of the URL. However, now that Janet includes source-maps for C functions, this results in incorrect links for these functions.
This PR fixes the links by testing whether the first entry in the source-map is `"boot.janet"` and if it is not, using the value of that first entry instead. Note that this test is necessary because bindings defined in `boot.janet` do not include the full path (i.e. `src/boot/boot.janet`). Perhaps they should but this would require changes to Janet itself.

Fix links to cfunction sources

---

content/docs/event_loop.mdz
content/docs/networking.mdz
content/docs/threads.mdz

An attempt to address https://github.com/janet-lang/janet-lang.org/issues/144

Move event loop docs before threads

---

Makefile

Quote env var values in `JSETTINGS`, because `$(PATH)` or `$(CWD)` may contain a special character.
Also quotes the output of `pwd`, just in case.

Quote environment variables and cwd in Makefile

---

content/docs/comparison.mdz

Add a new section on the *Comparison* page for the `deep=` operator.
The new section is pretty light, it's mostly just examples of how the operator compares to primitive equals.

Add documentation section on deep=

---

content/docs/jpm.mdz

This is an attempt to document the `:install true` key-value pair for the `declare-executable` form in `project.janet`.

Document `:install true` for `declare-executable`

---

content/docs/index.mdz

@levitanong reported on the janet-language/help channel about experiences with using the releases `.tar.gz` for Linux.
bakpakin provided clarification regarding the intention of that `.tar.gz`:
> So there seems to be significant discussion about installing Janet releases using the Tarball on linux - my advice there is use the build instructions and build from source instead. The tarball is mainly for people scripting releases - and this is the case for most software on various unixes, simply because it is expected that distros will link to different libc versions, turn on different optimization flags, etc.
This PR is an attempt to tweak the existing installation docs to better reflect the above information.

Tweak Linux install info

---

content/docs/data_structures/index.mdz

Clarify that you can use either, but you *specifically* want to use `in` for arrays, tuples, and string-likes if you want to better detect errors on bad keys.
Also more nicely aligned some comment values.
For some context and rationale for this PR, see https://github.com/janet-lang/janet/issues/953 .

data-structures, in and get clarification

---

content/docs/syntax.mdz

The tilde `~` is not valid in symbols

Removed tilde from crazy symbol

---

content/docs/functions.mdz

Just added two little small missing quotation marks that bothered me

fixed named arguments example in docs/functions

---

content/docs/syntax.mdz

IIUC, `\v` is also [considered whitespace](https://github.com/janet-lang/janet/blob/f27b225b34968e38a3131bafa963d78f92e3f7d6/src/core/parse.c#L39).

Add `\v` to list of things considered whitespace

---

content/docs/ffi.mdz

Was following along with the docs and found that as-is, the code wasn't working here.
Adding a parameter made things work.

Add missing parameter to ffi/signature call

---

content/docs/functions.mdz

I just realized that my last pull request added the quotation marks in the wrong place for the example to make sense
Also wording.

fixed example for named functions

---

content/docs/peg.mdz

Document the `number` special.
I compared `peg.c` against `peg.mdz` with `comm` and this is the only undocumented form.

Document (number) PEG special

---

content/docs/syntax.mdz

May be it's a bit nicer to express `NaN` as `math/nan` as the latter can be used in Janet code while the former doesn't currently seem to work out-of-the-box in the manner implied by the text.

Express NaN as math/nan

---

content/docs/threads.mdz

In my local testing, I'm observing supervisor events that are tuples with 3 elements, though the current website docs describe such events as being tuples of two elements.  Perhaps things changed at some point (or may be I'm doing something wrong (^^; )
Also, the keyword that's the first element of the tuple seems to currently be `:ok` and not `:done` for the non-error case.
This PR is an attempt to reflect these findings in the docs.
I've tried to describe the third element of the tuple based on code from [here](https://github.com/janet-lang/janet/blob/cabbaded68947a7be3bee5c5b9e0dff0a3963c48/src/core/ev.c#L548-L552).  Happy to change to a better description :)

Update supervisor event description

---

content/capi/configuration.mdz

This PR contains suggested changes to the configuration docs.  Some things included are:
* Removal of mention of the obsolete `thread` module
* Updating the list of `os` functions available that remain when `JANET_REDUCED_OS` is set
* Updating the list of `peg` functions that get disabled when `JANET_NO_PEG` is set
* Minor spelling / grammatical / wording tweaks
* Some wrapping changes for width-challenged situations

Tweak configuration docs

---

content/docs/ffi.mdz

Currently, the sample code blocks on the Foreign Function Interface page contain invalid syntax:
These snippets do not compile because the `@` is inside the `[`:
```
Janet 1.27.0-01aab666 linux/x64/gcc - '(doc)' for help
repl:1:> (def my-type (ffi/struct :char [@:int 4]))
repl:1:32: compile error: unknown symbol @:int
```
This PR fixes the sample code by moving the `@` outside the `[` in both code blocks:
```
Janet 1.27.0-01aab666 linux/x64/gcc - '(doc)' for help
repl:1:> (def my-type (ffi/struct :char @[:int 4]))
<core/ffi-struct 0x563C9B5EE910>
```

Fix typos in ffi/write and ffi/read code blocks

---

templates/docpage.html

This prevents sharing links to individual functions using the URL fragment, as autofocusing the searchbox will scroll to the top of the page.
Fixes #170

don't autofocus the search bar

---

examples/product.janet

The example for the `(product)` function contains a reference to `(sum)`, but functioning in context the way one would expect `(product)` to function. This was potentially introduced as a copy/paste error.

Incorrect function referenced in `(product)` example

---

content/capi/writing-c-functions.mdz

This PR contains minor suggestions regarding:
* spelling of a word
* the removal of one of the two rows for `%f`

Tweak format string table

---

content/docs/fibers/dynamic_bindings.mdz
content/docs/fibers/error_handling.mdz
content/docs/fibers/index.mdz

This PR contains some tweaks to the three fiber doc files:
* Index
* Dynamic Bindings
* Error Handling
One group of changes involves changing the sample code (using a table instead of a struct) and some of the claimed output [1] so that if one were following along by typing things in, the results would be more in line with the documentation.
The rest of the changes are minor suggestions, mostly about the prose.
---
[1] Current output for the sample code shows parentheses vs square brackets (which might have been the case when docs were written?).

Tweak fiber docs

---

content/docs/modules.mdz

This PR contains miscellaneous suggestions for the modules documentation.
Perhaps the most relevant change is for updating the code to the url loader example so that it no longer uses the deprecated `file/popen` call.  The changes were based on the content of [this file](https://github.com/janet-lang/janet/blob/15177ac2e9024d8f17ded07aefe07222f0dcda2e/examples/urlloader.janet).
The rest of the suggestions are fairly minor concerning prose, markup, and formatting (except in a couple of cases where the content of a comment was brought in line with relevant code).

Update modules doc

---

content/docs/data_structures/arrays.mdz
content/docs/data_structures/buffers.mdz
content/docs/data_structures/index.mdz
content/docs/data_structures/tables.mdz
content/docs/data_structures/tuples.mdz
content/docs/event_loop.mdz
content/docs/ffi.mdz
content/docs/gen-asm-table.janet
content/docs/index.mdz
content/docs/jpm.mdz
content/docs/linting.mdz
content/docs/loop.mdz
content/docs/networking.mdz
content/docs/peg.mdz
content/docs/strings.mdz

This PR contains a variety of suggestions (trying to align with [this](https://github.com/janet-lang/janet/blob/master/CONTRIBUTING.md#typo-fixing-and-one-line-changes)).
Among other things it contains:
* Changes to some code samples for consistency (e.g. tweak some naming, avoiding shadowing of built-in names, comments matching actual behavior, etc.)
* Changes to some identifiers (e.g. `fiber/root` instead of `fiber/root-fiber`, `math/nan` instead of `NaN`)
* Changes to one of the PEG tables (e.g. adding some missing info, swapping order of two rows, fixing the table where a row had leaked out, etc.)
* Change "Janet Package Manager" to "Janet Project Manager" to match the name in the jpm repository

Tweak function names, code, table content, etc.

---

content/docs/gen-asm-table.janet

This PR contains some suggestions for the abstract machine reference table.
Specifically the changes are:
* Added missing `dest` argument for `prop`
* Swapped the last two arguments of `puti`
* Changed spelling of `tcheck` to `tchck`
On a side note, regarding the argument swapping for `puti` -- the order was surprising to me given the pattern for `get`, `geti` and `put`.  I looked a bit at some history for it and it seems to have been that way for a long time.  Curious about the order.
Any hints?

Tweak abstract machine reference table

---

content/docs/syntax.mdz

Some escape sequences were added to Janet in [d6337e77](https://github.com/janet-lang/janet/commit/d63379e7777b1269ad4e8e075c971503b1732c30).  This PR is an attempt to update the PEG for Janet on the syntax page.
As the number of items is increasing, it seemed prudent to sort the items to make maintenance easier (e.g. avoidance of duplicates, locating a particular item, etc.).  The sorting order chosen was based on what was found via the ascii(7) man page.
In an attempt to reduce the amount of "backslashing", also changed the string delimiter to backtick.

Update and ascii-sort string escapes in peg

---

content/docs/documentation.mdz
content/docs/ffi.mdz
content/docs/jpm.mdz
content/docs/linting.mdz
content/docs/process_management/execute.mdz
content/docs/process_management/index.mdz
content/docs/process_management/spawn.mdz

This PR is an attempt to address #215.
This initial version covers two approaches to working with subprocesses in Janet, i.e. `os/execute` and `os/spawn`.
There are three pages:
* a brief introduction that could be expanded to accomodate additional things if necessary in some future pr (e.g. `os/posix-fork` and `os/posix-exec`)
* a page for `os/execute`
* a page for `os/spawn` and closely related functions such as `os/proc-wait` and `os/proc-close`
FWIW, this approach of splitting across pages is similar to that taken with the fibers section which also has multiple pages.
Thanks to:
* @amano-kenji for the j3blocks work and related feedback
* @bakpakin for the tips and pointers in the various related issues
* @llmII for the repeated reviews and many discussions

Add process management docs

---

content/docs/functions.mdz

This PR is an attempt to address #205.
It adds some text mentioning that a symbol can be placed after `&keys` (instead of a struct literal) and a code example that demonstrates the use.

Explain use of symbol after &keys (#205)

---

content/docs/modules.mdz

This PR is an attempt to address #208.
It adds a section to the Modules page for @-prefixed imports.
The text is close to:
```
@-prefixed Imports
Starting in 1.26.0, Janet allows importing modules from 
custom directories more easily using the @-prefix in a 
module path.
For example, if there is a dynamic binding 
:custom-modules that is a file system path to a 
directory of modules, import from that directory with:
(import @custom-modules/mymod)
As a special case, it is possible to import from 
absolute paths by prefixing an absolute path with @. 
For example, to import from 
/tmp/custom-modules/mymod.janet, express this as:
(import @/tmp/custom-modules/mymod)
Note that although using absolute paths is possible 
and useful for testing, it is not recommended for 
most production use …
```

Add @-prefixed import section

---

content/api/bundle.mdz

This PR proposes a new page under "API" for the `bundle/*` functions.

Add a module page for `bundle/*`

---

README.md

As the website top page is encouraging Zulip, this PR is a suggestion to sync the chat badge in the README.
The link was determined via [these instructions](https://zulip.com/help/linking-to-zulip).
[Déjà vu](https://github.com/janet-lang/janet/pull/1510)?

Replace gitter badge with zulip one

---

content/docs/specials.mdz

This PR is an attempt to address #223.
A couple of examples are added to the sample code for `fn` on the [Special forms page](https://janet-lang.org/1.36.0/docs/specials.html) showing that `fn` can be named via a symbol or a keyword.

Document that fn can be named

---

content/docs/fibers/index.mdz

This PR is an attempt to address #232.
My current hope is to pair it with an update to `signal`'s docstring with something like what's described [here](https://github.com/janet-lang/janet-lang.org/issues/232#issuecomment-2351351905).

Mention signal in fiber overview

---

content/docs/peg.mdz

This PR contains changes to the docs for the `look` peg special.
The docs do not currently appear to cover the case of `look` being called with only a single argument:
>    (look offset patt)
>    Matches only if patt matches at a fixed offset. offset can be any integer. patt will not produce captures and the peg will not advance any characters.
This PR attempts to cover this additional case.
Please see [here](https://github.com/janet-lang/janet/issues/1465) for some background.

Update look peg special docs

---

content/index.mdz

This PR is an attempt to address #222.
The initial content consists of:
* Creation of a separate editor section (broken out from being part of the "Modules and Libraries" section)
* An introductory paragraph explaining the content along with mentioning the "editors and tooling" discussion area in the Zulip Instance 
* Changing the list of currently supported editors
* Atom has been removed because it was sunset (the link wasn't leading anywhere useful AFAICT)
* Helix and TIC-80 were added
* The original ordering has been mostly preserved with new things being appended to the end of the list
* Each editor link [1] points to a page at [this repository](https://github.com/sogaiu/janet-editor-and-tooling-info/).  Each such page there describes some supported features along with some relevant …

Update editors info

---

content/api/gen-docs.janet

This PR is an attempt to address #244.
Please see that issue for some background.
---
If this PR is merged before https://github.com/janet-lang/janet-lang.org/pull/242, one of the files in that PR should probably have its filename changed.
The file in question is [this one](https://github.com/janet-lang/janet-lang.org/pull/242/files#diff-0c5d311e823c84570b14cdc6e4fb9444fac80719088c40b72d3cf090f7ecc1d5).  It is currently named `->.janet`, but likely a better name might end up being `-_62.janet`.

Make examples file naming friendlier to Windows

---

examples/string_47split.janet

As part of a Janetuary activity proposed by @erichaney, here are some examples for `string/split`.
I tried to keep things simple (and horizontally "friendly") and also tried to illustrate an edge case that tripped me up recently (^^;

Add examples for `string/split`

---

examples/keep.janet

add examples for keep

---

content/docs/peg.mdz

I added this earlier this year but never made a doc PR... until now.

document the (split) PEG special

---

examples/keep.janet

This PR swaps an example of `keep`.
The removal of one example is motivated by some comments starting [here](https://github.com/janet-lang/janet-lang.org/pull/258#issuecomment-2595925367).
Motivation for the additional example includes the points:
1. Use of a symbol in the predicate argument position that represents a pre-existing function instead of using a function constructed via the use of `fn` (as there are already examples of the latter)
2. Showing a use of `keep` which is in some sense about as simple as things might get

Swap an example for keep

---

content/docs/functions.mdz

In [a recent Zulip discussion](https://janet.zulipchat.com/#narrow/channel/399615-general/topic/Janetuary.20Community.20Project.3A.20Write.20API.20examples/near/494049217), there was some talk about the pipe reader macro and its current light coverage in the docs.
This PR is a suggestion to add a bit of prose and some examples to the [Functions page](https://janet-lang.org/1.37.1/docs/functions.html) with some coverage of the pipe reader macro and the associated `short-fn` macro.

Touch on pipe reader macro on functions page

---

.gitignore
static/css/docpage.css
static/css/landing.css
static/css/main.css

Hello, during my quest to learn Janet I often find myself browsing the site late at night and it's quite a strain on my eyes.
This PR minimally changes the 3 primary CSS files by adding media queries that use a dark theme when the user's OS/browser is set to dark.
In keeping with the style of the codebase, I've opted to inline colour values as opposed to using CSS variables. The majority of colours I've chosen are already present in the styling for the regular theme, save for one or two hand-picked shades of grey where necessary.
I've chosen to co-locate the media queries next to the classnames/ids that are affected. This leads to duplicated code (the same media selector) but simpler navigation.
Attached are some (very large) screenshots to give an idea of how the site looks with the …

Add dark theme

---

examples/short-fn.janet

Here are some examples for `short-fn`, including demonstration of the pipe reader macro: `|`.
If this gets merged, perhaps we can consider trimming the existing docstring [1] of `short-fn` of [its examples](https://github.com/janet-lang/janet/blob/2b49903c828c8667cbbbda4c5f4404d3bd3e7af1/src/boot/boot.janet#L2352-L2358) [2].
---
[1] Sort of along the lines of [this commit](https://github.com/janet-lang/janet/commit/5de889419ff26b710b706958bf99e180d084f564).
[2] Similar ones have been included in this PR.

Add examples for `short-fn`

---

examples/filter.janet

add examples for filter

---

examples/delay.janet

`delay` doesn't seem to map to the simple example format of `(foo) # -> output` Also, we don't really show `repl>` in other examples (maybe we should?)
Certainly open for suggestions.

add examples for delay

---

examples/def-.janet

This PR suggests tweaking the last example for `def-`.
The existing example didn't work as-is for the current version of janet (though may be it did when the example was added) so an attempt was made to get it to work based on an interpretation of the associated comment.
Original:
```janet
(def :private x private-thing :encapsulated)
```
Suggested change:
```janet
(def private-thing :private :encapsulated)
```

Tweak def- example

---

examples/reverse.janet

This PR suggests tweaking some of the examples for `reverse`.
The return value for the second example did not match recent behavior for janet so this was updated.
The third example was removed because the current docstring does not specify a behavior for operating on keywords:
> Reverses the order of the elements in a given array or tuple and returns a new array. If a string or buffer is provided, returns a buffer instead.

Tweak reverse examples

---

content/docs/index.mdz

I'm running Janet version `1.37.1-homebrew`.
See the introduction page at <https://janet-lang.org/docs/index.html>:
`(all-bindings)` does not 'print out' all global functions when executed in the REPL, rather it returns them.
```
$ janet
Janet 1.37.1-homebrew linux/x64/gcc - '(doc)' for help
repl:1:> (all-bindings)
@[% %= * ... yield zero? zipcoll]
repl:2:>
```
This is already alluded to in the welcome message of the REPL, and the README of `janet-lang/janet`:
> To get a list of all bindings in the default environment, use the (all-bindings) function. You can also use the (doc) macro with no arguments if you are in the REPL to show bound symbols.
The `(doc)` macro does print out all global functions when executed in the REPL:
```
$ janet
Janet 1.37.1-homebrew linux/x64/gcc - '(doc)' for …
```

Janet Introduction: Replace (all-bindings) with (doc) for REPL

---

content/docs/specials.mdz

In a [Zulip discussion about the `if` special form](https://janet.zulipchat.com/#narrow/channel/409517-help/topic/Scope.20within.20'if'.20special.20form), it came up that the [Special Forms page](https://janet-lang.org/1.37.1/docs/specials.html) doesn't appear to mention that `if` and `while` can introduce new lexical scopes (though the coverage for `do` and `fn` touch on the topic).
This PR suggests the addition of some text to remedy the situation.

Mention new scopes for if and while

---

README.md
content/api/examples.janet
content/api/gen-docs.janet

For background and motivation, please see [this comment](https://github.com/janet-lang/janet-lang.org/issues/256#issuecomment-2600807625).
This PR is a suggestion to address #256 by:
1. Exposing the ability to generate a suitable examples directory filename for a Janet symbol via a script
2. Updating the "Adding Examples" section of the README to explain how to use the script
As part of point 1 above, a portion of `content/api/gen-docs.janet` was relocated to a new file named `content/api/examples.janet`.  This latter file also contains a `main` entry point for use from the command line.
Use of the new script is also described in the udpated README, but a concrete invocation example is:
```
$ janet content/api/examples.janet array/new
```
which should yield the output:
``` …
```

Expose example filename creation via script

---

examples/slice.janet

This PR suggests tweaking some of the examples for `slice`.
The comment for the first example mentioned "a new array", but the return value is a tuple.  Since the input to `slice` is an array in this case, it seemed reasonable to remove the comment.
A number of the other examples used `[:a :b :d :d :e]` (note that there are two instances of `:d`) as an argument to `slice`, but based on the surrounding information, I suspect the intent was to use `[:a :b :c :d :e]` so this was altered in some cases.
Finally, I think error messages have changed since the original example was created so an update was made along those lines.

Tweak slice examples

---

content/index.mdz

This PR is an attempt to address the point made in [this comment](https://github.com/janet-lang/janet-lang.org/pull/248#issuecomment-2615559963).
The suggested change in this PR is to mention `(doc)` instead of `all-bindings` in the text.  Two positive points about this are:
1. Currently, use of `all-bindings` (with parens) may lead to truncated results in a default janet installation:
```
$ janet
Janet 1.37.1-fa75a395 linux/x64/gcc - '(doc)' for help
repl:1:> (all-bindings)
@[% %= * ... yield zero? zipcoll]
```
In contrast, `(doc)` gives nicer grouped output that isn't truncated and this seems more suitable for the situation in question.
2. The surrounding parens for the `(doc)` option might make it more likely that a newcomer might meet success sooner compared to `all-bindings` (which …

Suggest (doc) instead of all-bindings

---

content/docs/peg.mdz

This PR contains suggested changes to the documentation for the `look` peg special and attempts to address #281.
For background please see the following issues:
* https://github.com/janet-lang/janet/issues/1554
* https://github.com/janet-lang/janet-lang.org/issues/281
The changes include:
* Addressing the point made at the top of [this comment](https://github.com/janet-lang/janet/issues/1554#issuecomment-2629749471):
> I don't know when it was decided that lookahead should not produce captures, but in most cases they do. We should fix the docs here.
* Simplifying the form of the signature and overall text as:
> (look ?offset patt)
> Matches only if patt matches at a fixed offset. offset can be any integer and defaults to 0. The peg will not advance any characters.
I find the new version …

Tweak look peg special docs

---

examples/spork_47argparse_47argparse.janet

I am a janet noob so please let me know if I should change anything style-wise.

Add example for spork/argparse/argparse

---

examples/defn-.janet
examples/defn.janet
examples/eval-string.janet
examples/eval.janet
examples/loop.janet

This PR is an attempt to improve the consistency of some of the existing examples.
Apart from a minor adjustment to correct an example, the changes basically are of three types:
1. Try to use the `# -> <value>` comment to describe return values only
2. Try to use the `# -> error: ...` (or `# -> compile error: ...`, etc.) comment(s) to describe errors
3. Use comments to describe printed output -- AFAICT, this is more in line with how most of the other examples do things

Improve consistency of examples

---

examples/eachk.janet

add examples for eachk

---

examples/eachp.janet

add examples for eachp

---

examples/_42.janet
examples/apply.janet
examples/product.janet

This PR contains some minor tweaks to examples for `*`, `apply`, and `product`.
Apart from some formatting, some return values and an error message are modified.

Tweak examples: *, apply, and product

---

content/docs/index.mdz

I've updated the links and specified the individual components that are necessary.

Update Windows development instructions

---

content/docs/index.mdz

Previous commit [a334121](https://github.com/janet-lang/janet-lang.org/commit/a3341215b5a4515169df923cc2fe69de0da969b1) breaks the build on my system (and I assume for everyone else).
It appears that Mendoza is interpreting the "(you will need ..." text as a Janet statement.  This change prevents that and enables the build to complete.

Prevent recent text addition from being interpreted as a Janet statement

---

examples/map.janet

Here are some examples for `map`, including the use of multiple input data structures.
The examples are intended to demonstrate some of what has been spelled out in the docstring for `map` which was updated in [this commit](https://github.com/janet-lang/janet/commit/363e32d4557c939c8dbcb069a0a7578b5b594daf).

Add examples for map

---

examples/count.janet

Here are some examples for `count`, including the use of multiple input data structures and an illustration of an edge case.

Add examples for count

---

examples/all.janet

Here are a couple more examples for `all` which illustrate use of multiple input data structures.

Add more examples for all

---

examples/some.janet

Here are some examples for `some`, including the use of multiple input data structures.

Add examples for some

---

content/docs/functions.mdz

This PR is a suggestion to clarify the meaning of `$&` as [currently expressed on the function page](https://janet-lang.org/1.38.0/docs/functions.html):
```
Similarly, $0, $1, etc. refer to the arguments at index 0, 1,
etc. and $& refers to all passed arguments as a tuple.
```
IIUC, when `$`, `$0`, ..., `$i` is/are used, `$&` refers to less than "all passed arguments":
```janet
(|[$0 $1 $&] 1 0 -1)
[1 0 [-1]]
(|[$ $&] 1 0)
[1 [0]]
```
The suggested change is to express the above as:
```
Similarly, $0, $1, etc. refer to the arguments at index 0, 1,
etc. and $& refers to all remaining arguments as a tuple.
```
i.e. saying "all remaining arguments" instead of "all passed arguments".

Clarify meaning of $&

---

examples/mapcat.janet

Here are some examples for `mapcat`, including the use of multiple input data structures and an illustration of an edge case.

Add examples for mapcat

---

content/docs/syntax.mdz

Two of the Struct examples at https://janet-lang.org/docs/syntax.html#Structs-1 won't work on the REPL:
```lisp
$ janet
Janet 1.38.0-ddc12295 linux/x64/gcc - '(doc)' for help
repl:1:> {(1 2 3) (4 5 6)}
repl:1:2: compile error: 1 expects 1 argument, got 2
repl:2:> {'(1 2 3) '(4 5 6)}
{(1 2 3) (4 5 6)}
```
This PR changes 2 examples to the tuple literal (square brackets) that are introduced in the Tuples section right before Structs. For newcomers it's probably simpler to use the square brackets rather than using quote (```'```) at this point in the docs (`quote` is introduced in the Special Forms section, right after Structs).

Use square brackets in Tuples examples

---

content/index.mdz

The readme on Github says Janet supports more than the website does, so, so I updated the later one with two lined.
It might be an incomplete update, so there could be still some outdated info now on the website.

Sync feature list with readme

---

content/docs/data_structures/tuples.mdz

This came out of a conversation in Zulip.
Please make improvements if I missed or made anything unclear.

Rewrite bracketed tuples section with examples

---

content/api/gen-docs.janet
content/index.mdz

I hope these two templates cover it.
I wasn't sure whether I should change all the saved html - I was surprised by its presence in the repo instead of only templates. Swlkr said he will redirect .com to .org, so eventually the old ones will break (due to my new url scheme with package names) (deprecated bindings will break on the change, though). If you decide to change them, ctrl-f:
-  `janetdocs.com/` -> `janetdocs.org/core-api/` (note the `/`)
- `janetdocs.com"` -> `janetdocs.org"` (for indexes, note the `"`)

Change janetdocs.com to .org

---

content/docs/documentation.mdz

I've been examining in some detail the (hundreds of) existing Janet docstrings and think I've got a fairly good impression of which features are being used and which not so much [1].
This PR contains some suggested modifications to the description of the subset of Markdown supported by Janet docstrings.  It also includes some suggested changes to the terms used to more closely match what I encountered in the most recent [CommonMark spec](https://spec.commonmark.org/) and the [Markdown Syntax page](https://daringfireball.net/projects/markdown/syntax).  Also, I don't think block quotes are supported so I removed a mention of it.  FWIW, in its place, paragraphs are mentioned.
The changed text suggests the mentioning of:
* top-level paragraphs (placing multiple paragraphs in a list item may …

Tweak doc markdown subset description

---

content/docs/index.mdz

Typed_arrays was moved to jpm in 1.16 (1baab5eb)

Remove reference to typed_array
